from __future__ import annotations

from mi_fitness_sync.exceptions import MiFitnessError


COUNTRY_CODE_TO_REGION = {
    "AC": "sg",
    "AD": "de",
    "AE": "sg",
    "AF": "sg",
    "AG": "us",
    "AI": "us",
    "AL": "de",
    "AM": "sg",
    "AO": "sg",
    "AQ": "sg",
    "AR": "us",
    "AS": "sg",
    "AT": "de",
    "AU": "sg",
    "AW": "us",
    "AX": "de",
    "AZ": "sg",
    "BA": "de",
    "BB": "us",
    "BD": "sg",
    "BE": "de",
    "BF": "sg",
    "BG": "de",
    "BH": "sg",
    "BI": "sg",
    "BJ": "sg",
    "BL": "us",
    "BM": "us",
    "BN": "sg",
    "BO": "us",
    "BQ": "us",
    "BR": "us",
    "BS": "us",
    "BT": "sg",
    "BV": "sg",
    "BW": "sg",
    "BY": "de",
    "BZ": "us",
    "CA": "us",
    "CC": "sg",
    "CD": "sg",
    "CF": "sg",
    "CG": "sg",
    "CH": "de",
    "CI": "sg",
    "CK": "sg",
    "CL": "us",
    "CM": "sg",
    "CN": "cn",
    "CO": "us",
    "CR": "us",
    "CV": "sg",
    "CW": "us",
    "CX": "sg",
    "CY": "de",
    "CZ": "de",
    "DE": "de",
    "DG": "sg",
    "DJ": "sg",
    "DK": "de",
    "DM": "us",
    "DO": "us",
    "DZ": "sg",
    "EA": "de",
    "EC": "us",
    "EE": "de",
    "EG": "sg",
    "EH": "sg",
    "ER": "sg",
    "ES": "de",
    "ET": "sg",
    "FI": "de",
    "FJ": "sg",
    "FK": "us",
    "FM": "sg",
    "FO": "de",
    "FR": "de",
    "GA": "sg",
    "GB": "de",
    "GD": "us",
    "GE": "sg",
    "GF": "de",
    "GG": "de",
    "GH": "sg",
    "GI": "de",
    "GL": "us",
    "GM": "sg",
    "GN": "sg",
    "GP": "us",
    "GQ": "sg",
    "GR": "de",
    "GS": "us",
    "GT": "us",
    "GU": "sg",
    "GW": "sg",
    "GY": "us",
    "HK": "sg",
    "HN": "us",
    "HR": "de",
    "HT": "us",
    "HU": "de",
    "IC": "sg",
    "ID": "sg",
    "IE": "de",
    "IL": "sg",
    "IM": "de",
    "IN": "i2",
    "IO": "sg",
    "IQ": "sg",
    "IS": "de",
    "IT": "de",
    "JE": "de",
    "JM": "us",
    "JO": "sg",
    "JP": "sg",
    "KE": "sg",
    "KG": "sg",
    "KH": "sg",
    "KI": "sg",
    "KM": "sg",
    "KN": "us",
    "KR": "sg",
    "KW": "sg",
    "KY": "us",
    "KZ": "sg",
    "LA": "sg",
    "LB": "sg",
    "LC": "us",
    "LI": "de",
    "LK": "sg",
    "LR": "sg",
    "LS": "sg",
    "LT": "de",
    "LU": "de",
    "LV": "de",
    "LY": "sg",
    "MA": "sg",
    "MC": "de",
    "MD": "de",
    "ME": "de",
    "MF": "de",
    "MG": "sg",
    "MH": "sg",
    "MK": "de",
    "ML": "sg",
    "MM": "sg",
    "MN": "sg",
    "MO": "sg",
    "MP": "sg",
    "MQ": "us",
    "MR": "sg",
    "MS": "us",
    "MT": "de",
    "MU": "sg",
    "MV": "sg",
    "MW": "sg",
    "MX": "us",
    "MY": "sg",
    "MZ": "sg",
    "NA": "sg",
    "NC": "sg",
    "NE": "sg",
    "NF": "sg",
    "NG": "sg",
    "NI": "us",
    "NL": "de",
    "NO": "de",
    "NP": "sg",
    "NR": "sg",
    "NU": "sg",
    "NZ": "sg",
    "OM": "sg",
    "PA": "us",
    "PE": "us",
    "PF": "sg",
    "PG": "sg",
    "PH": "sg",
    "PK": "sg",
    "PL": "de",
    "PM": "us",
    "PN": "sg",
    "PR": "us",
    "PS": "sg",
    "PT": "de",
    "PW": "sg",
    "PY": "us",
    "QA": "sg",
    "RE": "sg",
    "RO": "de",
    "RS": "de",
    "RU": "ru",
    "RW": "sg",
    "SA": "sg",
    "SB": "sg",
    "SC": "sg",
    "SE": "de",
    "SG": "sg",
    "SH": "sg",
    "SI": "de",
    "SJ": "de",
    "SK": "de",
    "SL": "sg",
    "SM": "de",
    "SN": "sg",
    "SO": "sg",
    "SR": "us",
    "SS": "sg",
    "ST": "sg",
    "SV": "us",
    "SZ": "sg",
    "TA": "sg",
    "TC": "us",
    "TD": "sg",
    "TF": "sg",
    "TG": "sg",
    "TH": "sg",
    "TJ": "sg",
    "TK": "sg",
    "TL": "sg",
    "TM": "sg",
    "TN": "sg",
    "TO": "sg",
    "TR": "sg",
    "TT": "us",
    "TV": "sg",
    "TW": "sg",
    "TZ": "sg",
    "UA": "de",
    "UG": "sg",
    "UM": "us",
    "US": "us",
    "UY": "us",
    "UZ": "sg",
    "VA": "de",
    "VC": "us",
    "VG": "us",
    "VI": "us",
    "VN": "sg",
    "VU": "sg",
    "WF": "sg",
    "WS": "sg",
    "XK": "de",
    "YE": "sg",
    "YT": "sg",
    "ZA": "sg",
    "ZM": "sg",
    "ZW": "sg",
}


def normalize_country_code(value: str | None) -> str | None:
    if value is None:
        return None

    normalized = value.strip().upper()
    if not normalized:
        return None

    if len(normalized) != 2 or not normalized.isalpha():
        raise MiFitnessError(
            "Country overrides must use a two-letter country code such as ID, GB, or US."
        )

    return normalized


def region_for_country_code(value: str | None) -> str | None:
    country_code = normalize_country_code(value)
    if country_code is None:
        return None

    region = COUNTRY_CODE_TO_REGION.get(country_code)
    if region is None:
        raise MiFitnessError(f"Unsupported Mi Fitness country override: {country_code}.")

    return region
